"""Export TFLite model and feature extraction assets as C headers for Arduino.

Generates all header files needed by the car_sound_classifier Arduino sketch:
  - model_data.h      : TFLite model as aligned C byte array
  - mel_filterbank.h   : Sparse mel filterbank weights
  - normalization.h    : Per-band z-score mean/std arrays
  - hann_window.h      : 512-point Hann window coefficients

Usage:
    python src/export_for_arduino.py --model m6 --tier 2 --method ptq
    python src/export_for_arduino.py --model m2 --tier 2 --method ptq
    python src/export_for_arduino.py --model m5 --tier 2 --method ptq
"""

import argparse
import os
import sys
from pathlib import Path

import librosa
import numpy as np

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
import tensorflow as tf

# ─── Paths ────────────────────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = PROJECT_ROOT / "models"
DATA_DIR = PROJECT_ROOT / "data"
DEFAULT_OUTPUT = PROJECT_ROOT / "arduino" / "car_sound_classifier"

# Model directory and normalization stats mapping
MODEL_INFO = {
    "m2": {
        "ptq_dir": "m3_cnn2d_int8_ptq",
        "qat_dir": "m4_cnn2d_int8_qat",
        "float_dir": "m2_cnn2d_float32",
        "condition": "combined",
        "stats_file": "normalization_stats_combined.npz",
        "feature_type": "mel",
        "display_name": "2-D CNN (M2)",
    },
    "m5": {
        "ptq_dir": "m5_cnn1d_int8_qat",
        "qat_dir": "m5_cnn1d_int8_qat",
        "float_dir": "m5_cnn1d_int8_qat",
        "condition": "standard",
        "stats_file": "normalization_stats_augmented.npz",
        "feature_type": "mfcc",
        "display_name": "1-D CNN (M5)",
    },
    "m6": {
        "ptq_dir": "m6_dscnn_int8_qat",
        "qat_dir": "m6_dscnn_int8_qat",
        "float_dir": "m6_dscnn_int8_qat",
        "condition": "standard",
        "stats_file": "normalization_stats_augmented.npz",
        "feature_type": "mel",
        "display_name": "DS-CNN (M6)",
    },
}

# Mel-spectrogram parameters (from data/preprocessing_config.json)
SAMPLE_RATE = 16000
N_FFT = 512
HOP_LENGTH = 256
N_MELS = 40
FMIN = 20
FMAX = 8000
N_FRAMES = 92  # floor((24000 - 512) / 256) + 1

# Tier 2 class names
TIER2_CLASSES = [
    "Normal Braking", "Braking Fault", "Normal Idle",
    "Idle Fault", "Normal Start-Up", "Start-Up Fault",
]


# ─── Header Generation ────────────────────────────────────────────────────


def export_model_data(tflite_path: str, output_path: str, model_name: str) -> dict:
    """Convert .tflite to C header and extract quantization params."""
    with open(tflite_path, "rb") as f:
        model_bytes = f.read()

    # Extract quantization params from the model
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()

    inp = interpreter.get_input_details()[0]
    out = interpreter.get_output_details()[0]

    input_scale = float(inp["quantization"][0])
    input_zp = int(inp["quantization"][1])
    output_scale = float(out["quantization"][0])
    output_zp = int(out["quantization"][1])
    input_shape = inp["shape"].tolist()
    output_shape = out["shape"].tolist()
    num_classes = output_shape[-1]

    # Get ops list (excluding DELEGATE which is PC-only)
    try:
        ops_details = interpreter._get_ops_details()
        ops = sorted(set(d["op_name"] for d in ops_details if d["op_name"] != "DELEGATE"))
    except Exception:
        ops = ["UNKNOWN"]

    # Write C header
    with open(output_path, "w") as f:
        f.write(f"// Auto-generated by src/export_for_arduino.py\n")
        f.write(f"// Model: {model_name} from {tflite_path}\n")
        f.write(f"// Size: {len(model_bytes)} bytes ({len(model_bytes)/1024:.1f} KB)\n")
        f.write(f"// Input: {input_shape} int8, scale={input_scale:.10f}, zp={input_zp}\n")
        f.write(f"// Output: {output_shape} int8, scale={output_scale:.10f}, zp={output_zp}\n")
        f.write(f"// TFLite ops: {', '.join(ops)}\n")
        f.write(f"//\n")
        f.write(f"// Required MicroMutableOpResolver ops:\n")
        op_map = {
            "CONV_2D": "AddConv2D()",
            "DEPTHWISE_CONV_2D": "AddDepthwiseConv2D()",
            "FULLY_CONNECTED": "AddFullyConnected()",
            "MAX_POOL_2D": "AddMaxPool2D()",
            "MEAN": "AddMean()",
            "SOFTMAX": "AddSoftmax()",
            "RESHAPE": "AddReshape()",
            "EXPAND_DIMS": "AddExpandDims()",
            "AVERAGE_POOL_2D": "AddAveragePool2D()",
        }
        for op in ops:
            resolver_call = op_map.get(op, f"// TODO: Add{op}()")
            f.write(f"//   resolver.{resolver_call};\n")
        f.write(f"\n")
        f.write(f"#ifndef MODEL_DATA_H\n")
        f.write(f"#define MODEL_DATA_H\n\n")
        f.write(f"#include <stdint.h>\n\n")
        f.write(f"// Quantization parameters\n")
        f.write(f"#define INPUT_SCALE  {input_scale:.10f}f\n")
        f.write(f"#define INPUT_ZERO_POINT  {input_zp}\n")
        f.write(f"#define OUTPUT_SCALE {output_scale:.10f}f\n")
        f.write(f"#define OUTPUT_ZERO_POINT {output_zp}\n")
        f.write(f"#define NUM_OPS {len(ops)}\n\n")
        f.write(f"// Model data\n")
        f.write(f"alignas(16) const unsigned char g_model_data[] = {{\n")

        # Write bytes in rows of 12
        for i in range(0, len(model_bytes), 12):
            chunk = model_bytes[i : i + 12]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"  {hex_str},\n")

        f.write(f"}};\n")
        f.write(f"const unsigned int g_model_data_len = {len(model_bytes)};\n\n")
        f.write(f"#endif // MODEL_DATA_H\n")

    return {
        "input_scale": input_scale,
        "input_zp": input_zp,
        "output_scale": output_scale,
        "output_zp": output_zp,
        "input_shape": input_shape,
        "num_classes": num_classes,
        "ops": ops,
        "size_bytes": len(model_bytes),
    }


def export_mel_filterbank(output_path: str) -> None:
    """Export sparse mel filterbank as C header."""
    mel_fb = librosa.filters.mel(
        sr=SAMPLE_RATE, n_fft=N_FFT, n_mels=N_MELS, fmin=FMIN, fmax=FMAX,
    )
    # Shape: (40, 257)

    # Extract sparse representation
    filters = []
    all_weights = []
    for m in range(N_MELS):
        nz_indices = np.nonzero(mel_fb[m])[0]
        if len(nz_indices) > 0:
            start_bin = int(nz_indices[0])
            end_bin = int(nz_indices[-1])
            num_weights = end_bin - start_bin + 1
            weights = mel_fb[m, start_bin : end_bin + 1].tolist()
        else:
            start_bin = 0
            num_weights = 0
            weights = []
        filters.append((start_bin, num_weights))
        all_weights.extend(weights)

    total_weights = len(all_weights)

    with open(output_path, "w") as f:
        f.write("// Auto-generated by src/export_for_arduino.py\n")
        f.write(f"// Sparse mel filterbank: {N_MELS} filters, {total_weights} non-zero weights\n")
        f.write(f"// Generated from librosa.filters.mel(sr={SAMPLE_RATE}, n_fft={N_FFT}, "
                f"n_mels={N_MELS}, fmin={FMIN}, fmax={FMAX})\n\n")
        f.write("#ifndef MEL_FILTERBANK_H\n#define MEL_FILTERBANK_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define MEL_NUM_FILTERS {N_MELS}\n")
        f.write(f"#define MEL_TOTAL_WEIGHTS {total_weights}\n")
        f.write(f"#define MEL_NUM_FFT_BINS {N_FFT // 2 + 1}\n\n")

        f.write("typedef struct {\n")
        f.write("  uint16_t start_bin;\n")
        f.write("  uint16_t num_weights;\n")
        f.write("} MelFilterInfo;\n\n")

        f.write(f"const MelFilterInfo mel_filter_info[{N_MELS}] = {{\n")
        for start, nw in filters:
            f.write(f"  {{{start}, {nw}}},\n")
        f.write("};\n\n")

        f.write(f"const float mel_filter_weights[{total_weights}] = {{\n")
        for i in range(0, total_weights, 8):
            chunk = all_weights[i : i + 8]
            f.write("  " + ", ".join(f"{w:.8f}f" for w in chunk) + ",\n")
        f.write("};\n\n")

        f.write("#endif // MEL_FILTERBANK_H\n")

    print(f"  Mel filterbank: {N_MELS} filters, {total_weights} weights, "
          f"{total_weights * 4 + N_MELS * 4} bytes")


def export_normalization(stats_file: str, output_path: str) -> None:
    """Export per-band normalization statistics as C header."""
    stats = np.load(stats_file)
    mel_mean = stats["mel_mean"].astype(np.float32)
    mel_std = stats["mel_std"].astype(np.float32)

    with open(output_path, "w") as f:
        f.write("// Auto-generated by src/export_for_arduino.py\n")
        f.write(f"// Normalization stats from {Path(stats_file).name}\n\n")
        f.write("#ifndef NORMALIZATION_H\n#define NORMALIZATION_H\n\n")

        f.write(f"const float mel_norm_mean[{len(mel_mean)}] = {{\n")
        for i in range(0, len(mel_mean), 8):
            chunk = mel_mean[i : i + 8]
            f.write("  " + ", ".join(f"{v:.6f}f" for v in chunk) + ",\n")
        f.write("};\n\n")

        f.write(f"const float mel_norm_std[{len(mel_std)}] = {{\n")
        for i in range(0, len(mel_std), 8):
            chunk = mel_std[i : i + 8]
            f.write("  " + ", ".join(f"{v:.6f}f" for v in chunk) + ",\n")
        f.write("};\n\n")

        # Also export MFCC stats for M5 fallback
        if "mfcc_mean" in stats:
            mfcc_mean = stats["mfcc_mean"].astype(np.float32)
            mfcc_std = stats["mfcc_std"].astype(np.float32)
            f.write(f"const float mfcc_norm_mean[{len(mfcc_mean)}] = {{\n")
            f.write("  " + ", ".join(f"{v:.6f}f" for v in mfcc_mean) + ",\n")
            f.write("};\n\n")
            f.write(f"const float mfcc_norm_std[{len(mfcc_std)}] = {{\n")
            f.write("  " + ", ".join(f"{v:.6f}f" for v in mfcc_std) + ",\n")
            f.write("};\n\n")

        f.write("#endif // NORMALIZATION_H\n")


def export_hann_window(output_path: str) -> None:
    """Export Hann window coefficients as C header."""
    # Use numpy's hanning which produces the periodic form matching librosa
    window = np.hanning(N_FFT).astype(np.float32)

    with open(output_path, "w") as f:
        f.write("// Auto-generated by src/export_for_arduino.py\n")
        f.write(f"// {N_FFT}-point periodic Hann window\n\n")
        f.write("#ifndef HANN_WINDOW_H\n#define HANN_WINDOW_H\n\n")
        f.write(f"const float hann_window[{N_FFT}] = {{\n")
        for i in range(0, N_FFT, 8):
            chunk = window[i : i + 8]
            f.write("  " + ", ".join(f"{v:.8f}f" for v in chunk) + ",\n")
        f.write("};\n\n")
        f.write("#endif // HANN_WINDOW_H\n")


# ─── Main ─────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description="Export TFLite model + assets for Arduino")
    parser.add_argument("--model", required=True, choices=["m2", "m5", "m6"],
                        help="Model architecture")
    parser.add_argument("--tier", type=int, default=2, choices=[1, 2, 3],
                        help="Taxonomy tier (default: 2)")
    parser.add_argument("--method", default="ptq", choices=["ptq", "qat"],
                        help="Quantization method (default: ptq)")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT),
                        help="Output directory for headers")
    args = parser.parse_args()

    info = MODEL_INFO[args.model]
    output_dir = Path(args.output)
    os.makedirs(output_dir, exist_ok=True)

    # Resolve TFLite model path
    if args.model == "m2":
        model_dir = info["ptq_dir"] if args.method == "ptq" else info["qat_dir"]
        tflite_name = f"tier{args.tier}.tflite"
    else:
        model_dir = info["ptq_dir"]  # Both PTQ and QAT are in the same dir
        if args.method == "ptq":
            tflite_name = f"tier{args.tier}_ptq.tflite"
        else:
            tflite_name = f"tier{args.tier}.tflite"

    tflite_path = str(MODELS_DIR / model_dir / tflite_name)

    if not os.path.exists(tflite_path):
        print(f"ERROR: TFLite model not found: {tflite_path}")
        sys.exit(1)

    print(f"Exporting {info['display_name']} Tier {args.tier} ({args.method.upper()})")
    print(f"  Source: {tflite_path}")
    print(f"  Output: {output_dir}/")
    print()

    # 1. Model data header
    print("Generating model_data.h...")
    model_info = export_model_data(
        tflite_path,
        str(output_dir / "model_data.h"),
        f"{info['display_name']} Tier {args.tier} {args.method.upper()}",
    )
    print(f"  Model: {model_info['size_bytes']} bytes ({model_info['size_bytes']/1024:.1f} KB)")
    print(f"  Input: {model_info['input_shape']}, scale={model_info['input_scale']:.6f}, zp={model_info['input_zp']}")
    print(f"  Output: {model_info['num_classes']} classes")
    print(f"  Ops: {', '.join(model_info['ops'])}")

    # 2. Mel filterbank (same for all mel-spectrogram models)
    print("\nGenerating mel_filterbank.h...")
    export_mel_filterbank(str(output_dir / "mel_filterbank.h"))

    # 3. Normalization stats
    print("\nGenerating normalization.h...")
    stats_path = str(DATA_DIR / info["stats_file"])
    export_normalization(stats_path, str(output_dir / "normalization.h"))
    print(f"  From: {info['stats_file']} (Condition {'B' if info['condition'] == 'standard' else 'D'})")

    # 4. Hann window
    print("\nGenerating hann_window.h...")
    export_hann_window(str(output_dir / "hann_window.h"))
    print(f"  {N_FFT}-point periodic Hann window")

    # Summary
    print(f"\n{'=' * 50}")
    print(f"Export complete. Generated files in {output_dir}/:")
    for f in sorted(output_dir.glob("*.h")):
        size = f.stat().st_size
        print(f"  {f.name}: {size:,} bytes ({size/1024:.1f} KB)")

    print(f"\nAdd to config.h:")
    print(f"  #define MODEL_NAME \"{info['display_name']} Tier {args.tier} {args.method.upper()}\"")
    print(f"  #define NUM_CLASSES {model_info['num_classes']}")
    print(f"  #define TENSOR_ARENA_SIZE {'51200' if args.model == 'm6' else '81920' if args.model == 'm2' else '25600'}")


if __name__ == "__main__":
    main()
